name: 'Step 1: Prep Release'
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The target branch'
        required: false
      version_spec:
        type: choice
        description: 'Version options'
        options:
          - major
          - minor
          - patch
          - prerelease
          - none
        required: true
        default: 'patch'

jobs:
  prep_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      # -------------------
      # Setup environment in remote runner
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9.*'

      # -------------------
      # Install tracker
      - name: Install tracker
        run: pip install -e .

      - name: Prep Release
        id: prep-release
        uses: jupyter-server/jupyter_releaser/.github/actions/prep-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN   }}
          version_spec: ${{ github.event.inputs.version_spec }}
          branch: ${{ github.event.inputs.branch }}
          since: ${{ github.event.inputs.since }}
          since_last_stable: ${{ github.event.inputs.since_last_stable }}

      - name: '** Next Step **'
        run: |
          echo "Optional): Review Draft Release: ${{ steps.prep-release.outputs.release_url }}"
