name: 'Publish Release using jupyter-releaser'
on:
  workflow_dispatch:
    inputs:
      version_spec:
        type: choice
        description: 'version options'
        options:
          - major
          - minor
          - patch
          - prerelease
          - none
        required: true
        default: 'patch'
      branch:
        description: 'The target branch'
        required: false
      release_url:
        description: 'The URL of the draft GitHub release'
        required: false
      steps_to_skip:
        description: 'Comma separated list of steps to skip'
        required: false

jobs:
  release-npmjs:
    runs-on: ubuntu-latest
    steps:
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      # -------------------
      # Checkout code
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      # -------------------
      # Setup environment in remote runner
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # -------------------
      # Install the package and all its dependencies
      # Needs to do this after bumping the version, otherwise
      # package.__version__ will point to the previous version
      - name: Install current package
        run: |
          pip install --upgrade pip
          pip install .[dev]
          pip list

      # -------------------
      # install build
      - name: Install pypa/build
        run: >-
          python -m pip install build

      # Install node
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.x
          cache: npm

      # -------------------
      # Install client packages
      - name: Install client packages
        run: npm install

      # -------------------
      # Compile typescript code
      - name: Compile raitracker
        run: npm run build

      # -------------------
      # Build wheel
      - name: Build wheel
        run: python -m build

      # -------------------
      # Install tracker
      - name: Install tracker
        run: pip install -e .

      - name: npm pack
        shell: bash
        run: |
          npm pack --pack-destination dist

      - name: Prep Release
        id: prep-release
        uses: jupyter-server/jupyter_releaser/.github/actions/prep-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version_spec: ${{ github.event.inputs.version_spec }}
          post_version_spec: ${{ github.event.inputs.post_version_spec }}
          branch: ${{ github.event.inputs.branch }}
          since: ${{ github.event.inputs.since }}
          since_last_stable: ${{ github.event.inputs.since_last_stable }}

      - name: Populate Release
        id: populate-release
        uses: jupyter-server/jupyter_releaser/.github/actions/populate-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.inputs.branch }}
          release_url: ${{ steps.prep-release.outputs.release_url }}
          steps_to_skip: ${{ github.event.inputs.steps_to_skip }}

      - name: Finalize Release
        id: finalize-release
        env:
          #   PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          #   PYPI_TOKEN_MAP: ${{ secrets.PYPI_TOKEN_MAP }}
          #   TWINE_USERNAME: __token__
          NPM_TOKEN: ${{ secrets.NPMJS_API_TOKEN }}
        uses: jupyter-server/jupyter-releaser/.github/actions/finalize-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release_url: ${{ steps.populate-release.outputs.release_url }}

      - name: '** Next Step **'
        if: ${{ success() }}
        run: |
          echo "Verify the final release" >> $GITHUB_OUTPUT
          echo ${{ steps.finalize-release.outputs.release_url }} >> $GITHUB_OUTPUT
      - name: '** Failure Message **'
        if: ${{ failure() }}
        run: |
          echo "Failed to Publish the Draft Release Url:" >> $GITHUB_OUTPUT
          echo ${{ steps.populate-release.outputs.release_url }} >> $GITHUB_OUTPUT
