name: 'Publish Release using jupyter-releaser'
on:
  workflow_dispatch:
    inputs:
      version_spec:
        type: choice
        description: 'version options'
        options:
          - major
          - minor
          - patch
          - prerelease
          - none
        required: true
        default: 'none'
      branch:
        description: 'The target branch'
        required: false
      release_url:
        description: 'The URL of the draft GitHub release'
        required: false
      steps_to_skip:
        description: 'Comma separated list of steps to skip'
        required: false

jobs:
  release-npmjs:
    runs-on: ubuntu-latest
    steps:
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Prep Release
        id: prep-release
        uses: jupyter-server/jupyter_releaser/.github/actions/prep-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version_spec: ${{ github.event.inputs.version_spec }}
          post_version_spec: ${{ github.event.inputs.post_version_spec }}
          target: ${{ github.event.inputs.target }}
          branch: ${{ github.event.inputs.branch }}
          since: ${{ github.event.inputs.since }}
          since_last_stable: ${{ github.event.inputs.since_last_stable }}

      - name: '** Next Step **'
        run: |
          echo "Optional): Review Draft Release: ${{ steps.prep-release.outputs.release_url }}"

      - name: Upload Distributions
        uses: actions/upload-artifact@v2
        with:
          name: dist-${{ github.run_number }}
          path: .jupyter_releaser_checkout/dist

      # -------------------
      # Commit the changes performed by the bump
      # Also, tag the current commit with the version number
      - name: commit new setup file
        if: ${{ github.event.inputs.bumpType != 'none' }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add package.json raitracker/_version.py
          git commit -m "update version number"
          VERSION=$(python bump_version.py 'none')
          git tag -a $VERSION -m "Release $VERSION"

      - name: Populate Release
        id: populate-release
        uses: jupyter-server/jupyter_releaser/.github/actions/populate-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ github.event.inputs.target }}
          branch: ${{ github.event.inputs.branch }}
          release_url: ${{ steps.prep-release.outputs.release_url }}
          steps_to_skip: ${{ github.event.inputs.steps_to_skip }}

      # -------------------
      # Push the changes performed by bump2version to the current branch
      - name: Push changes
        if: ${{ github.event.inputs.bumpType != 'none' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Finalize Release
        id: finalize-release
        env:
          # PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          # PYPI_TOKEN_MAP: ${{ secrets.PYPI_TOKEN_MAP }}
          # TWINE_USERNAME: __token__
          NPM_TOKEN: ${{ secrets.NPMJS_API_TOKEN }}
        uses: jupyter-server/jupyter-releaser/.github/actions/finalize-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ github.event.inputs.target }}
          release_url: ${{ steps.populate-release.outputs.release_url }}

      - name: '** Next Step **'
        if: ${{ success() }}
        run: |
          echo "Verify the final release"
          echo ${{ steps.finalize-release.outputs.release_url }}
      - name: '** Failure Message **'
        if: ${{ failure() }}
        run: |
          echo "Failed to Publish the Draft Release Url:"
          echo ${{ steps.populate-release.outputs.release_url }}
