name: 'Step 2: Publish Release'
on:
  workflow_dispatch:
    inputs:
      target:
        description: 'The owner/repo GitHub target'
        required: true
      bumpType:
        type: choice
        description: 'Version options'
        options:
          - major
          - minor
          - patch
          - prerelease
          - none
        required: true
        default: 'patch'
      branch:
        description: 'The target branch'
        required: false
      release_url:
        description: 'The URL of the draft GitHub release'
        required: false
      steps_to_skip:
        description: 'Comma separated list of steps to skip'
        required: false

jobs:
  release-npmjs:
    runs-on: ubuntu-latest
    steps:
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      # -------------------
      # Setup environment in remote runner
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # -------------------
      # Install the package and all its dependencies
      # Needs to do this after bumping the version, otherwise
      # package.__version__ will point to the previous version
      - name: Install current package
        run: |
          pip install --upgrade pip
          pip install .
          pip list

      # -------------------
      # install build
      - name: Install pypa/build
        run: >-
          python -m pip install build --user

      # -------------------
      # Install node
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.x
          cache: npm

      # -------------------
      # Install client packages
      - name: Install client packages
        run: npm install

      # -------------------
      # Compile typescript code
      - name: Compile raitracker
        run: npm run build

      # -------------------
      # Build wheel
      - name: Build wheel
        run: python -m build

      # -------------------
      # Install tracker
      - name: Install tracker
        run: pip install -e .

      - name: Populate Release
        id: populate-release
        uses: jupyter-server/jupyter_releaser/.github/actions/populate-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN   }}
          target: ${{ github.event.inputs.target }}
          branch: ${{ github.event.inputs.branch }}
          release_url: ${{ github.event.inputs.release_url }}
          steps_to_skip: ${{ github.event.inputs.steps_to_skip }}

      - name: Finalize Release
        id: finalize-release
        env:
          PYPI_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
          PYPI_TOKEN_MAP: ${{ secrets.PYPI_TOKEN_MAP }}
          TWINE_USERNAME: __token__
          NPM_TOKEN: ${{ secrets.NPMJS_API_TOKEN }}
        uses: jupyter-server/jupyter-releaser/.github/actions/finalize-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ github.event.inputs.target }}
          release_url: ${{ steps.populate-release.outputs.release_url }}

      - name: '** Next Step **'
        if: ${{ success() }}
        run: |
          echo "Verify the final release"
          echo ${{ steps.finalize-release.outputs.release_url }}

      - name: '** Failure Message **'
        if: ${{ failure() }}
        run: |
          echo "Failed to Publish the Draft Release Url:"
          echo ${{ steps.populate-release.outputs.release_url }}
